export const Roles = {
    ADMIN: 'ADMIN',
    CREATOR: 'CREATOR',
    CUSTOMER: 'CUSTOMER',
}

export const VERIFY_CODE_TYPES = {
    VALIDATE_EMAIL: 'VALIDATE_EMAIL',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
}

export const PRODUCT_STATUS = {
    PUBLISHED: 'PUBLISHED',
    PENDING_REVIEW: 'PENDING_REVIEW',
    DRAFTS: 'DRAFTS',
}

// export const PRODUCT_CATEGORY = {
//     PRINTS: 'PRINTS',
//     WALL_SCROLLS: 'WALL_SCROLLS',
//     DAKIMAKURAS: 'DAKIMAKURAS',
//     T_SHIRTS: 'T_SHIRTS',
//     ARYLIC_SATANDEES: 'ARYLIC_SATANDEES',
//     COMICS: 'COMICS',
//     PLAYMATS: 'PLAYMATS',
//     ART_BOOKS: 'ART_BOOKS',
//     TOWELS: 'TOWELS',
//     ERGONOMIC_MOUSEPADS: 'ERGONOMIC_MOUSEPADS',
//     MYSTERY_BOXES: 'MYSTERY_BOXES',
//     NULLS: 'NULLS' 
// }

export const USER_STATUS = {
    PENDING: 'PENDING',
    ACTIVATE: 'ACTIVATE',
    DEACTIVATE: 'DEACTIVATE',
    SUSPENDED: 'SUSPENDED',
}

export const DEFAULT_PRODUCT_SIZE = {
    '1x1': '1x1',
    '3x7': '3x7',
}

export const CHECKOUT_STATUS = {
    PAYMENT_ISSUE: 'PAYMENT_ISSUE',
    PENDING: 'PENDING',
    SHIPPED: 'SHIPPED',
    COMPLETED: 'COMPLETED',
    ISSUE: 'ISSUE',
}

export const RORYALTY_STATUS = {
    PAID: 'PAID',
    UNPAID: 'UNPAID',
}

export const PRODUCT_SELL_TYPE = {
    DIGITAL: 'DIGITAL',
    PHYSICAL: 'PHYSICAL',
}