name: Deploy Inkedfur

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy backend 
    runs-on: ubuntu-latest
    env: 
      SERVER_PASSWORD: ${{secrets.PASSWORD}}
    # steps:
      

    #   # - name: Install Dependencies
    #   #   run: |
    #   #     npm install
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0  # Specify the Node.js version you need
          
      - name: Set up bash
        run: |
          sudo ln -sf /bin/bash /bin/sh

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /root/inkedfur-v3-backend-cicd
            git pull origin main
            npm install